site_name: vertLab
site_url: https://spaghetmenot.github.io/vertlab/

theme:
  name: material
  custom_dir: overrides
  font:
    text: Ubuntu
    code: Red Hat Mono
  logo: assets/subDMagicIcon.png
  favicon: assets/subDMagicIcon.png
  features:
    - navigation.tracking
    - navigation.indexes
    # - navigation.expand
    # - navigation.path
    # - navigation.prune
    - navigation.sections
    # - navigation.tabs
    
    # - navigation.top
    - toc.follow

  palette:  
  # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: black
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - toc:
      permalink: true

extra:
  # social:
  #   - icon: simple/bluesky
  #     link: https://bsky.app/profile/spaghetmenot.bsky.social
  #   - icon: simple/mastodon
  #     link: https://mastodon.social/@SpaghetMeNot
  #   - icon: simple/x
  #     link: https://x.com/SpaghetMeN0t
  #   - icon: simple/youtube
  #     link: https://www.youtube.com/@SpaghetMeNot
  generator: false
  version:
    provider: mike
    default: latest
    alias: true



plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: black
      shadow: true
      manual: false
    